### ISSUE TITLE
Return error instead of just an error message

### ISSUE THREAD

**Issue by Sicria** [teamplanes/graphql-rate-limit#169]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

Is it possible to return an error object from the ``formatError`` method rather than just a message?

Internally we use predefined errors which include meta data. To get these errors consistent when using this package we have to add a handler and check if the error has ``isRateLimitError`` field, then we format the error. 

If we were able to return an error from the method it would align with ``graphql-shield`` as it allows returning of errors rather than just strings for error messages.

Thank you for a great package!

**Comment by Bram-Zijp** [comment]
Where is this error thrown? It is very unclear how "inconsistent" the current error handling is in your situation.

**Comment by wu-json** [comment]
I would love this feature as well. In my particular use-case, I would like to throw an `ApolloError` instance with error code 429 to communicate this to the client. Would be nice to be able to set a `fallbackError` similar to what `graphql-shield` does.

**Comment by Bram-Zijp** [comment]
Probably didn't look at this well enough. It is possible to specify a custom error handler (I guess this should work):
```
const rateLimiter = getGraphQLRateLimiter({ identifyContext: (ctx) => ctx.id, formatError: ({ fieldName }) => new ApolloError(`Woah there, you are doing way too much ${fieldName}` }) });
```

@wu-json I don't think we should be setting Apollo errors in this module. This module is not tied to Apollo per se.
