### ISSUE TITLE
Do I have any ways to use graphql-rate-limit only by express-graphql ?  

### ISSUE THREAD

**Issue by garysdevil** [teamplanes/graphql-rate-limit#17]
Do I have any ways to use graphql-rate-limit only by express-graphql ?

**Comment by kirkness** [comment]
Yes sure, it all depends on how you write your schema. For example if you use `makeExecutableSchema`, then you'd do:

```js

makeExecutableSchema({
  // ...
  schemaDirectives: {
    rateLimit: rateLimitDirective,
  },
})
```

**Comment by garysdevil** [comment]
> > Yes sure, it all depends on how you write your schema. For example if you use `makeExecutableSchema`, then you'd do:
> > ```js
> > makeExecutableSchema({
> >   // ...
> >   schemaDirectives: {
> >     rateLimit: createRateLimitDirective({
> >       identifyContext: ctx => ctx.req.ip,
> >     })
> >   },
> > })
> > ```
> 
> 👌！Thank you a lot.
> There are 2 questions:
> 1 Could I install graphql-rate-limit by npm ?
> 2 Do I have any ways to set two rules at once ? Just like
> " course(id: Int!): Course @ratelimit(max: 5, window: "60s") @ratelimit(max: 1, window: "1s") "

**Comment by garysdevil** [comment]
cool !
