### ISSUE TITLE
Ability to default rate limit directive fields to apply globally..

### ISSUE THREAD

**Issue by DeeJEarl88** [teamplanes/graphql-rate-limit#174]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
I am unable to default the directive fields instead of declaring them each time i add the directive to a type definition  

Example:
directive @rateLimit(
    max: Int = 2
    window: String = "60s"
    message: String = "Test"
) on FIELD_DEFINITION

**Comment by kirkness** [comment]
Hi @DeeJEarl88 - cheers for the question. This has been spoken about [here](https://github.com/teamplanes/graphql-rate-limit/issues/21).
