### ISSUE TITLE
Library fails on npm install

### ISSUE THREAD

**Issue by alexbjorlig** [teamplanes/graphql-rate-limit#175]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
When I try to install with npm, clean master branch, I get the this error:

```
npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: graphql-rate-limit@2.0.1
npm ERR! Found: eslint@5.3.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"5.3.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">=5.9.0" from eslint-plugin-ava@6.0.0
npm ERR! node_modules/eslint-plugin-ava
npm ERR!   dev eslint-plugin-ava@"^6.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by Bram-Zijp** [comment]
Happy to look into this. Could you provide a reproduction?

**Comment by alexbjorlig** [comment]
Hi @Bram-Zijp - I almost forgot about graphql-rate-limit and was super close to start rolling my own solution 😅  But I just tried reproducing the issue, and everything seems to work when doing npm installs today 🚀 Looking forward to try out the library.
