### ISSUE TITLE
Do I have any ways to set two rules at once ? 

### ISSUE THREAD

**Issue by garysdevil** [teamplanes/graphql-rate-limit#18]
2 Do I have any ways to set two rules at once ? Just like
" course(id: Int!): Course @ratelimit(max: 5, window: "60s") @ratelimit(max: 1, window: "2s") "

but this can't work!

**Comment by ravangen** [comment]
A graphql-js RFC exists to add [support for repeatable directives (#1541)](https://github.com/graphql/graphql-js/pull/1541). This is to adjust the spec's [Directives Are Unique Per Location](https://facebook.github.io/graphql/June2018/#sec-Directives-Are-Unique-Per-Location). Currently, multiple `@rateLimit` directives could not be defined on the same location.

A workaround that I have been exploring in my own toy graphql-rate-limit package is to allow the same directive to be given multiple different names. For example, `@rateLimitBurst` and `@rateLimitSustain`.

It's cool to see others try to tackle this problem too 👍

**Comment by kirkness** [comment]
Using different names could work, however with the way the cache works you'd likely run into problems as the field calls aren't namespaced per directive name.

**Comment by garysdevil** [comment]
> Using different names could work, however with the way the cache works you'd likely run into problems as the field calls aren't namespaced per directive name.

Sorry, I'm a little confused. Could you write a simple example?

**Comment by ravangen** [comment]
A potential alternative I think to [step 1](https://github.com/teamplanes/graphql-rate-limit#step-1):

```typescript
const storeBurst = new InMemoryStore();
const storeSustain = new InMemoryStore();

const GraphQLRateLimitBurst = createRateLimitDirective({
  store: storeBurst,
});
const GraphQLRateLimitBurst = createRateLimitDirective({
  store: storeSustain,
});
```

The key point is you want isolation between what the directives use to keep track of usage. Having separate stores that use different prefixes could accomplish this.

**Comment by kirkness** [comment]
Ah, of course - yes the above should work. The key is that you have 2 separate stores.

**Comment by garysdevil** [comment]
> Ah, of course - yes the above should work. The key is that you have 2 separate stores.

Cool . But if I use the default InMemoryStore  I cant't do it , am I right?

**Comment by garysdevil** [comment]
I have a another question that can we set  identifyContext:  ctx.user.id and ctx.req.ip or how

**Comment by ravangen** [comment]
> > Ah, of course - yes the above should work. The key is that you have 2 separate stores.
> 
> Cool . But if I use the default InMemoryStore I cant't do it , am I right?

Correct, the [`defaultConfig`](https://github.com/teamplanes/graphql-rate-limit/blob/master/src/lib/field-directive.ts#L75-L85) is reused across multiple directive classes and instances unless you provide an override `store` to `customConfig` like https://github.com/teamplanes/graphql-rate-limit/issues/18#issuecomment-456828168 does.

> I have a another question that can we set identifyContext: ctx.user.id and ctx.req.ip or how

I may be misunderstanding the question, but you can define your own `identifyContext` function to build a string with both pieces of data. For example, `identifyContext()` could return `'f65e6fb0-1e14-4ad4-928b-6047149a704b 127.0.0.1'`.

```javascript
const identifyContext = (ctx) => `${ctx.user.id} ${ctx.req.ip}`;
const GraphQLRateLimit = createRateLimitDirective({ identifyContext });
```

**Comment by garysdevil** [comment]
> > > Ah, of course - yes the above should work. The key is that you have 2 separate stores.
> > 
> > 
> > Cool . But if I use the default InMemoryStore I cant't do it , am I right?
> 
> Correct, the [`defaultConfig`](https://github.com/teamplanes/graphql-rate-limit/blob/master/src/lib/field-directive.ts#L75-L85) is reused across multiple directive classes and instances unless you provide an override `store` to `customConfig` like [#18 (comment)](https://github.com/teamplanes/graphql-rate-limit/issues/18#issuecomment-456828168) does.
> 
> > I have a another question that can we set identifyContext: ctx.user.id and ctx.req.ip or how
> 
> I may be misunderstanding the question, but you can define your own `identifyContext` function to build a string with both pieces of data. For example, `identifyContext()` could return `'f65e6fb0-1e14-4ad4-928b-6047149a704b 127.0.0.1'`.
> 
> ```js
> const identifyContext = (ctx) => `${ctx.user.id} ${ctx.req.ip}`;
> const GraphQLRateLimit = createRateLimitDirective({ identifyContext });
> ```

Cool ! It work.
