### ISSUE TITLE
Inactive repo, needs new maintainers?

### ISSUE THREAD

**Issue by Bram-Zijp** [teamplanes/graphql-rate-limit#180]
Are there any maintainers left? I added an [PR long](https://github.com/teamplanes/graphql-rate-limit/pull/171) ago and it is not moving. Should we assign new maintainers or make a generic fork?

**Comment by kirkness** [comment]
Hey @Bram-Zijp, apologies for the lack of response on your PR. I've stretched myself a little thin on this and so have been slow to review and integrate new work. Although it is my intention to pick this back up. That said, I'd welcome additional maintainers if you are keen?

Will review your PR now.

**Comment by Bram-Zijp** [comment]
I wouldn't mind helping out! I'm planning on using it in future projects so it makes sense.

**Comment by kirkness** [comment]
Awesome, I've just invited you as a collaborator. We don't have automated releases on this repo yet which would be handy for multiple maintainers. For now, I'll just publish manually when PR's are merged.

**Comment by wu-json** [comment]
@kirkness I would also love to contribute if possible! Particularly interested in [Issue #169.](https://github.com/teamplanes/graphql-rate-limit/issues/169)

**Comment by kirkness** [comment]
Hey @wu-json, I'll get you added as a collaborator tomorrow! Cheers

**Comment by kirkness** [comment]
Sent invite @wu-json (@Bram-Zijp you also have a pending invite).

**Comment by Bram-Zijp** [comment]
@kirkness my invitation has expired. Could you resend it?

**Comment by kirkness** [comment]
👍  done.
