### ISSUE TITLE
What is the breaking change in 3.0?

### ISSUE THREAD

**Issue by chemicalkosek** [teamplanes/graphql-rate-limit#182]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
I see a major bump, but can't find info in changelog on what is the breaking change in 3.0.
(Please add to changelog)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by kirkness** [comment]
Some background on why we released as a major [here](https://github.com/teamplanes/graphql-rate-limit/pull/179#issuecomment-829333654).

**Comment by kirkness** [comment]
Manual update of changelog [here](https://github.com/teamplanes/graphql-rate-limit/blob/master/CHANGELOG.md)... need to automate!
