### ISSUE TITLE
Apollo/Gateway integration

### ISSUE THREAD

**Issue by sbilello** [teamplanes/graphql-rate-limit#186]
I'm submitting a question about how to use this project

* **Summary**

How is it possible to integrate with the apollo/gateway in a federated graph?

**Comment by kirkness** [comment]
As long as you have the `schema` object you can implement with `graphql-middleware`, i'd recommend using `graphql-shield` to do so: https://github.com/teamplanes/graphql-rate-limit#option-2-using-the-graphql-shield
