### ISSUE TITLE
Allow set global rate limits for being applied to all the queries/mutations

### ISSUE THREAD

**Issue by swcarlosrj** [teamplanes/graphql-rate-limit#21]
* **I'm submitting a ...**
[x] feature request

* **Summary**
It'd be cool be able to set global limits for all the queries/mutations, I'd probably wanna set `window: "60s", max: 100` for all of them and include the @rateLimit directive wherever I wanna be more specific

It could be an example:
```
createRateLimitDirective({
  ...,
  global: {
    max: '100', 
    window: '60s',
    message: 'You are doing that too often'
  }
}
```

**Comment by kirkness** [comment]
👍- it should, in theory, be possible using [directive defaults](https://www.apollographql.com/docs/graphql-tools/schema-directives.html) but I've just tried it and it doesn't. I'll get this looked into!

Would look like:
```graphql
  directive @rateLimit(
    max: Int = 2
    window: String = "10s"
    message: String
    identityArgs: [String]
  ) on FIELD_DEFINITION
```

**Comment by swcarlosrj** [comment]
Awesome, looking forward to test such a feature. Thanks 😄

**Comment by swcarlosrj** [comment]
I just gave a look to directive defaults, it looks great but afaik it requires to add `@rateLimit` directive in every single Query, Mutations, Subscription field as follow:
```graphql
type Query {
  capsules(...) @rateLimit
  capsulesPast(...) @rateLimit
  capsulesUpcoming(...) @rateLimit
  capsule	(...) @rateLimit
  ...
  rockets(...) @rateLimit
  rocket(...) @rateLimit
  ships(...) @rateLimit
}
```

Talking about global confs, it'd not make sense. Idk if it'd be possible specifying a global conf object, add the directives dynamically, that'd be 🔥

**Comment by kirkness** [comment]
Ah ok, so you mean that you could apply a rate limit to all queries at the same time?

Perhaps something like this could be nice:

```graphql
type Query @rateLimit  {
    capsules(...)
  capsulesPast(...)
  capsulesUpcoming(...)
  capsule	(...)
  ...
  rockets(...)
  rocket(...)
  ships(...)
}
```

**Comment by swcarlosrj** [comment]
Yep, that looks 💯! And having this
```graphql
type Query @rateLimit {
  capsules(...) @rateLimit(window: "1s", max: 5)
  capsulesPast(...)
  capsulesUpcoming(...)
  capsule(...)
  ...
  rockets(...)
  rocket(...)
  ships(...)
}
```

I guess, all the `queries` would have the global/default conf and `capsules` would apply the given values, smth like that!

**Comment by kirkness** [comment]
This is now possible using the graphql-sheild integration.

**Comment by scriptonist** [comment]
@kirkness Can you help us with a small snippet of how it can be achieved with graphql-shield ?

**Comment by kirkness** [comment]
Hello! Sure you can do it using the [graphql-shield wild-card feature](https://github.com/maticzav/graphql-shield#per-type-wildcard-rule).

So:

```
const rateLimitRule = ...
const permissions = {
  Query: {
   "*": rateLimitRule,
  }
}
```
