### ISSUE TITLE
Using Merge-graphql-schema, doesn't seem to work?

### ISSUE THREAD

**Issue by JulianSpring** [teamplanes/graphql-rate-limit#23]
* **I'm submitting a ...**
[ x] question about how to use this project

* **Summary**
Hi there, this is such an awesome looking project!

I was wondering if it works with merge-graphql-schema. It doesn't seem to be.
We have about 11 .graphql files that we merge.

Here is how the schema is set up.
```
const typeDefs = mergeTypes(fileLoader(path.join(__dirname, '../dist/src/schema')), {all: true});
const resolversMerged = mergeResolvers(fileLoader(path.join(__dirname, '../dist/src/resolvers')));
const GraphQLRateLimit = createRateLimitDirective({});
const context = ({req}) => {
    let auth = undefined;
    if (req) {
        auth = req.auth;
    }
    return {auth, requestIPAddress: req.connection.remoteAddress}
};

const schema = makeExecutableSchema({
    typeDefs: typeDefs,
    resolvers: resolversMerged,
    schemaDirectives: {
        rateLimit: GraphQLRateLimit
    }
});
```

**Comment by kirkness** [comment]
You need to add an `identifyContext` as per the docs: https://github.com/teamplanes/graphql-rate-limit#step-1

Let me know if it helps.

**Comment by kirkness** [comment]
Assuming you got this fixed, so closing!
