### ISSUE TITLE
[Question] Fixed size time window vs. Query cost/complexity validation

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [teamplanes/graphql-rate-limit#27]
I'm interested in pros and cons in using fixed size time window vs. query cost/complexity validation for securing GraphQL API from malicious queries.

Is using fixed size time window approach enough (provides no less (equal? more?) protection than query cost/complexity validation)? Or is it better to use both?

E.g. depth and amount limiting provides insufficient protection (less than query cost/complexity validation). See https://blog.apollographql.com/securing-your-graphql-api-from-malicious-queries-16130a324a6b. And its use is enough (if you use query cost/complexity validation, no need to use the depth and amount limiting).

Is fixed size time window approach easier to implement than query cost/complexity validation?

E.g. the query cost/complexity validation requires to define how complex certain resolvers are via the performance tracking data exposed by Apollo Engine.

**Comment by kirkness** [comment]
Hey @FluorescentHallucinogen, yes, in my opinion, it is best to use both as they both solve different problems. For example, cost/complexity validation might prevent a malicious user running this query:

```gql
query {
  items(total: 100000) {
    id
    items(total: 1000000) {
       items(total: 1000000) {
          items(total: 1000000) {
           ...
         }
      }
    }
  }
}
```

The above would obviously hammer your database and probably shut it down. However, with rate limiting, you could prevent a user from brute-forcing a password, or even just prevent them from creating more content than they should on your platform.
