### ISSUE TITLE
Re-add changelog

### ISSUE THREAD

**Issue by brortao** [teamplanes/graphql-rate-limit#29]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
I can see that `CHANGELOG.md` was recently deleted. There are no releases in the GitHub repo. This makes it very difficult to work out what's new in a new version: for example, 2.0.0 was recently released. We're upgrading from 1.x.x and I have no idea if there are any breaking changes, or what change warranted the major version bump. It'd be really nice if there was a changelog (and if the project followed semantic versioning).

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by kirkness** [comment]
You are right, apologies for any confusion with this. The API and functionality for existing users remain the same, v2 added the ability to use the rate limiter without the directive syntax. I wanted to be as cautious as I could in releasing, even knowing the release was good to go, hence why I didn't follow convention.

I'll add the changelog with the next release.
