### ISSUE TITLE
onError() method

### ISSUE THREAD

**Issue by buraksak35** [teamplanes/graphql-rate-limit#31]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

I need to create Log when trigger rate limit so I need onError() etc method. Is there any way handle to error? Like onError({contextIdentity}) => {} ? ( not using option 3 )

**Comment by kirkness** [comment]
Hey @buraksak35, whats the specific use-case here? Would [`formatError`](https://github.com/teamplanes/graphql-rate-limit#formaterror) do the trick?

**Comment by buraksak35** [comment]
@kirkness thank you for your answer. I used my app formatError and handled it. ( checked rate limit error or not  )
