### ISSUE TITLE
Skip / Filter

### ISSUE THREAD

**Issue by elrumordelaluz** [teamplanes/graphql-rate-limit#33]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

* **Summary**
Hi and thank for this useful library.
I am wondering if there is a way to set a `skip` (or `filter`) logic like in [this library](https://github.com/nfriedly/express-rate-limit#skip).

I am using it right now with some logic inside the `resolver` through [getGraphQLRateLimiter](https://github.com/teamplanes/graphql-rate-limit#option-3-using-the-base-rate-limiter-function) but since I also need to apply the `rate-limit` onto another _Mutations_ (without extra logic, so probably) using the other methods I am wondering if there is a way to set everithing using `createRateLimitDirective` to avoid declare the _RateLimit_ in two different places. 

Thanks!

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by kirkness** [comment]
Hello, what kind of conditions are you looking to check? I think it sounds like you've taken the best approach. Do you have an example?
