### ISSUE TITLE
Unable to get it to work with type-graphql

### ISSUE THREAD

**Issue by ssbiswal1987** [teamplanes/graphql-rate-limit#63]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ x ] question about how to use this project

* **Summary**
I have been trying to use the base rate limiter function to create a rate limiter and use with type-graphql as a middleware, but it is not working. It goes into the middleware but error is always undefoned

`
import { MiddlewareFn } from "type-graphql";
import { getGraphQLRateLimiter } from 'graphql-rate-limit';

const RateLimit: MiddlewareFn<any> = async ({ root: parent, args, context, info }, next) => {
	const rateLimiter = getGraphQLRateLimiter({
		formatError: () => {
			return 'Stop doing that.';
		},
		identifyContext: context => {
			return context.username;
		}
	});

	const errorMessage = await rateLimiter(
		{
			parent,
			args,
			context,
			info
		},
		{
			max: 2,
			window: '10s'
		}
	);
	if (errorMessage) throw new Error(errorMessage);

	return next();
};

export default RateLimit;
`

above is my middleware

and I use it like

`i
mport { Resolver, Query, Arg, Ctx, Authorized, UseMiddleware } from 'type-graphql';
import CurrencyExchange from '../types/CurrencyExchange';
import RateLimit from '../authentication/rateLimiter';

@Resolver()
export default class CurrenciesResolver {
	@UseMiddleware(RateLimit)
	@Query(returns => [CurrencyExchange])
	async currenciesWithExchange(
		@Arg('currencyCodes', type => [String]) currencyCodes: string[],
		@Ctx() ctx: any
	): Promise<CurrencyExchange[]> {
		const { dataSources } = ctx;

		return await dataSources.currencyApi.getCurrenciesWithExchangeRates(currencyCodes);
	}
}
`

Any idea what am I doing wrong. As, I understand this should work with in memory.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by KiziKr** [comment]
It can be because you declare rateLimiter in your middleware and it must not exist anymore.

try to declare outside in other file

**Comment by ssbiswal1987** [comment]
I fixed it by defining my rate limiter outside the middleware. The rate limiter was created everytime the middleware was run.
